title: Calculadora Cientifica/Converión
lang: es
description: Proyecto final de calculadora y conversora
remote_theme: pages-themes/merlot@v0.2.0

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-them
